// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtVPjuNbL4B22TPn2D15Z38oFlT66gL_I',
    appId: '1:1052777881118:web:ef965a53b4ac021bc2980f',
    messagingSenderId: '1052777881118',
    projectId: 'evahan-40dcd',
    authDomain: 'evahan-40dcd.firebaseapp.com',
    storageBucket: 'evahan-40dcd.firebasestorage.app',
    measurementId: 'G-DEPYSY5GQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58kzWnuQFFPasqIycJazw26dwZzXy5eo',
    appId: '1:1052777881118:android:743848a9de48dba5c2980f',
    messagingSenderId: '1052777881118',
    projectId: 'evahan-40dcd',
    storageBucket: 'evahan-40dcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjF2JkXfXAaOR2RpQnOThyL3RQbnRt_w',
    appId: '1:1052777881118:ios:ed8d1685a43ceb3ec2980f',
    messagingSenderId: '1052777881118',
    projectId: 'evahan-40dcd',
    storageBucket: 'evahan-40dcd.firebasestorage.app',
    iosBundleId: 'com.example.evahan',
  );
}
